### ISSUE TITLE
FirePython ua-string might be blocked by some websites

### ISSUE THREAD

**Issue by fcurella** [binaryage/firelogger.py#2]
FirePython add 'X-FirePython/0.1' to the user-agent string.

Some websites (eg. wordreference.com) prevent bot access blocking user-agent with 'Python' in the useragent string.

**Comment by darwin** [comment]
This was already fixed in v0.3

http://github.com/darwin/firelogger/commit/aaeb68c4034f066e88d206b47b6e0649beadee77
