### ISSUE TITLE
middleware WSGI

### ISSUE THREAD

**Issue by laurentluce** [binaryage/firelogger.py#5]
I did the following:
- install firepython and jsonpickle
- add firepython.middleware.FirePythonDjango and firepython.middleware.FirePythonWSGI to MIDDLEWARE_CLASSES.

My setup is the following:
- django 1.1 - manage.py run as a thread
- lighttpd with fcgi enabled

Everything works fine without FirePython but I really want to use that great debug tool. When I add the 2 classes, all http request passed to manage.py timeout.

manage.py is up and running but seems to not handle any requests anymore.

Any help would be appreciated.

Laurent Luce

**Comment by darwin** [comment]
I'm sorry, django is really not an area of my expertise

btw. why are you adding both Django and WSGI into MIDDLEWARE_CLASSES?
you should add there only Django which should do all the magic

**Comment by laurentluce** [comment]
Sorry, I got confused with the term WSGI. I thought I needed that middleware too. Removing it did the trick, it is working fine now. Thanks.

**Comment by darwin** [comment]
WSGI is for hooking into pure WSGI stack (ie. naked Google App Engine), closing
