### ISSUE TITLE
Any percent signs in my output are showing up as blocks filled with the work 'undefined'

### ISSUE THREAD

**Issue by natethelen** [binaryage/firelogger.py#6]
Using 0.7 on the client and 0.5 on the server

So for example if I log a URL that has a %20 in it:

http://myurl.com/someurl?key=my%20value

It shows up like this:

http://myurl.com/someurl?key=myundefined20value

**Comment by darwin** [comment]
First parameter is always formatting string, percentage has a special meaning, javascript tries to replace it with parameter, you have two options:
1) logging.debug("%s", mystring)
2) replace all occurences of % in mystring for %% (aka escaping) and do logging.debug(mystring)

in future version I will fix this case, and don't replace percentages which have no remaining parameters

**Comment by natethelen** [comment]
Neither of these work because they mess up the messages in the files.  I have the firepython logger as a 2nd log output.

**Comment by natethelen** [comment]
I have tried going into the _prepare_log_record function in middleware.py and do #2 above, but it just shows up as 2: "undefined""undefined" in the firebug logger

**Comment by darwin** [comment]
fixed in http://github.com/darwin/firelogger/commit/f75a4b6b859614417886fa121f02fdb9a9bb882e

you can test it by checking out appstats branch and using rake to build XPI
