### ISSUE TITLE
WSGIMiddleware fails in the trunk

### ISSUE THREAD

**Issue by aadis** [binaryage/firelogger.py#7]
On trunk, the WSGI middleware fails for output_wrapper

Changing to:
                output = list(app_iter)
from:
                output = outer_wrapper(app_iter)
works

**Comment by darwin** [comment]
firepython needs to consume whole WSGI response, then set headers and then send whole output, reverting piranha's merge, closed by 3a2d27c366c89ad07114bb460044ad95d9ce9d39
